# Colors (PaperColor - Light)
colors:
  # Default colors
  primary:
    background: '#eeeeee'
    foreground: '#878787'

  cursor:
    text: '#eeeeee'
    cursor: '#878787'

  # Normal colors
  normal:
    black:   '#eeeeee'
    red:     '#af0000'
    green:   '#008700'
    yellow:  '#5f8700'
    blue:    '#0087af'
    magenta: '#878787'
    cyan:    '#005f87'
    white:   '#444444'

  # Bright colors
  bright:
    black:   '#bcbcbc'
    red:     '#d70000'
    green:   '#d70087'
    yellow:  '#8700af'
    blue:    '#d75f00'
    magenta: '#d75f00'
    cyan:    '#005faf'
    white:   '#005f87'