window:
  startup_mode: Maximized

# font:
#   normal:
#     family: FiraCode Nerd Font Mono

schemes:
  selenized_dark: &dark
    primary:
      background: '0x103c48'
      foreground: '0xadbcbc'
    normal:
      black:   '0x184956'
      red:     '0xfa5750'
      green:   '0x75b938'
      yellow:  '0xdbb32d'
      blue:    '0x4695f7'
      magenta: '0xf275be'
      cyan:    '0x41c7b9'
      white:   '0x72898f'
    bright:
      black:   '0x2d5b69'
      red:     '0xff665c'
      green:   '0x84c747'
      yellow:  '0xebc13d'
      blue:    '0x58a3ff'
      magenta: '0xff84cd'
      cyan:    '0x53d6c7'
      white:   '0xcad8d9'
  selenized_light: &light
    primary:
      background: '0xfbf3db'
      foreground: '0x53676d'
    normal:
      black:   '0xece3cc'
      red:     '0xd2212d'
      green:   '0x489100'
      yellow:  '0xad8900'
      blue:    '0x0072d4'
      magenta: '0xca4898'
      cyan:    '0x009c8f'
      white:   '0x909995'
    bright:
      black:   '0xd5cdb6'
      red:     '0xcc1729'
      green:   '0x428b00'
      yellow:  '0xa78300'
      blue:    '0x006dce'
      magenta: '0xc44392'
      cyan:    '0x00978a'
      white:   '0x3a4d53'

colors: *dark
