#!/bin/sh

set -e

export BINDIR=~/.local/bin
export PATH=~/.go/bin:~/.local/bin:$PATH

# Install dotfiles and all tools
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply smores56

# Create SSH key
if ! test -e ~/.ssh/id_ed25519.pub; then
  mkdir -p ~/.ssh
  ssh-keygen -t ed25519 -b 4096 -C $(hostname)
fi

# Log in to GitHub via CLI
if ! test -e ~/.config/gh/hosts.yml; then
  gh auth login --git-protocol=ssh --scopes=admin:public_key
fi

# Add SSH key to GitHub
PUBLIC_KEY=$(cat ~/.ssh/id_ed25519.pub | cut -d " " -f 2)
if ! curl -L https://github.com/smores56.keys | grep "$PUBLIC_KEY" 1>/dev/null; then
  gh ssh-key add ~/.ssh/id_ed25519.pub -t "$(hostname)"
fi

# Use SSH auth for dotfiles repo
cd $(chezmoi source-path)
git remote set-url origin git@github.com:smores56/dotfiles.git
