# Use C-a as the prefix
set -g prefix C-a
unbind C-b

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1
bind-key 0 select-window -t :10

# Allows for faster key repetition
set -s escape-time 0

# Reload config file
bind-key r source-file ~/.tmux.conf \; display-message 'Config reloaded...'

# Don't rename windows automatically
set-option -g allow-rename off

# Enable mouse mode
set-option -g mouse on

# Keep colors pretty
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# set theme
source-file "${HOME}/.tmux/gruvbox-${THEME}.conf"

# split windows
bind-key v split-window -h
bind-key s split-window -v

# alt-arrow to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# alt-n and alt-p to cycle windows, respectively
bind -n M-n next-window
bind -n M-p previous-window
