os:
  edit: helix -- {{filename}}
  editAtLine: helix -- {{filename}}:{{line}}
  editAtLineAndWait: helix -- {{filename}}:{{line}}
  editInTerminal: true

git:
  paging:
    colorArg: always
    pager: delta --paging=never --light

gui:
  theme:
    lightTheme: true
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
