# Use system theme
theme = "rose_pine_moon"

[editor]
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal.space]
s = ":write"
c = ":quit"
t = "hover"
