[[language]]
name = "rust"
config.rust-analyzer.diagnostics.disabled = ["unresolved-proc-macro"]

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
auto-format = true
