[[language]]
name = "rust"

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "svelte"
auto-format = true
roots = ["package.json"]

[[language]]
name = "nix"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "json"
auto-format = false

[[language]]
name = "roc"
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
shebangs = ["roc"]
roots = []
comment-token = "#"
language-servers = ["roc-ls"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "roc", args = ["format", "--stdin", "--stdout"] }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[[grammar]]
name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "ef46edd0c03ea30a22f7e92bc68628fb7231dc8a" }

[language-server.roc-ls]
command = "roc_language_server"

[language-server.rust-analyzer.config.rust-analyzer.diagnostics]
disabled = ["unresolved-proc-macro"]
