[[language]]
name = "rust"
config.rust-analyzer.diagnostics.disabled = ["unresolved-proc-macro"]

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "svelte"
auto-format = true
roots = ["package.json"]
