# add number line to side of screen
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching

# use simple title
set-option global ui_options ncurses_set_title=false

# convenient mappings (easy commands, comments, etc.)
map global normal / /(?i)
map global normal <a-/> <a-/>(?i)
map global normal "#" ": comment-line<ret>"
map global normal <c-w> ": w<ret>"
map global normal <c-q> ": q<ret>"
map global normal <c-Q> ": wq<ret>"

# change indentation in insert mode with tab
map global insert <tab> "<a-;><gt>"
map global insert <s-tab> "<a-;><lt>"

# set tab widths per language
hook global WinSetOption filetype=(java|rust|python|elm) %{ set-option buffer indentwidth 4 }
hook global WinSetOption filetype=(svelte|yaml|crystal|javascript|typescript|purescript|css|html|markdown) %{
    set-option buffer indentwidth 2
}

# wrap text in txt and markdown files
hook global WinSetOption filetype=(markdown|plain|yaml) %{
    add-highlighter buffer/ wrap
    add-highlighter buffer/ show-whitespaces
}

# add spell check for text files
set-option global spell_lang en-US
hook global WinSetOption filetype=(markdown|plain) %{
    spell
    hook buffer BufWritePost .* spell
}

# clipboard integration
map -docstring "copy to system clipboard"                   global normal 'y' '<a-|>xsel -b -i<ret>:<space>echo -markup %{{Information}yanked selection to system clipboard}<ret>'
map -docstring "cut to system clipboard"                    global normal 'd' '|xsel -b -i<ret>'
map -docstring "cut to system clipboard, enter insert mode" global normal 'c' '|xsel -b -i<ret>i'
map -docstring "paste from system clipboard before cursor"  global normal 'P' '!xsel --output --clipboard<ret>'
map -docstring "paste from system clipboard after cursor"   global normal 'p' '<a-!>xsel --output --clipboard<ret>'
map -docstring "replace selection with system clipboard"    global normal 'R' '|xsel --output --clipboard<ret>'

# import plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# import plugins
plug "robertmeta/plug.kak" noload

# save root-level files
plug "occivink/kakoune-sudo-write"

# git mode
plug 'jordan-yee/kakoune-git-mode' config %{
    map global user g ': enter-user-mode git<ret>' -docstring "git mode"

    hook global WinCreate .* %{ evaluate-commands %sh{
        if [ $kak_buffile != $kak_bufname ] && git ls-files --error-unmatch "$kak_buffile" > /dev/null 2>&1; then
            echo "git-mode-show-diff"
        fi
    }}

    hook global BufWritePost .* git-mode-update-diff
    hook global BufReload .* git-mode-update-diff
}

# status line
plug "andreyorst/powerline.kak" defer powerline %{
    set-option global powerline_format 'bufname filetype lsp mode_info line_column position'

    colorscheme gruvbox
    powerline-theme gruvbox
} config %{
    powerline-start
}

# setup lsp plugin
plug "kak-lsp/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    # debug to temp file
    set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'
    set global lsp_hover_max_lines 15

    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
    hook global WinSetOption filetype=(c|cpp|rust|elm|typescript|javascript|crystal|yaml|svelte|python) %{
        set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filtetype %opt{filetype}"
        lsp-enable-window

        map global user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
    }

    hook global WinSetOption filetype=(c|cpp|rust|elm|typescript|javascript|crystal|svelte|python) %{
        hook window BufWritePre .* lsp-formatting-sync
    }

    hook global WinSetOption filetype=(rust) %{
        set window lsp_server_configuration rust.clippy_preference="on"
    }

    hook global KakEnd .* lsp-exit
}

# hook global WinSetOption filetype=rust %{
#   hook window -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
#   hook window -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
#   hook window -group rust-inlay-hints InsertIdle .* rust-analyzer-inlay-hints
#   hook -once -always window WinSetOption filetype=.* %{
#     remove-hooks window rust-inlay-hints
#   }
# }
