[colors.bright]
black = "#9893a5"
blue = "#56949f"
cyan = "#d7827e"
green = "#286983"
magenta = "#907aa9"
red = "#b4637a"
white = "#575279"
yellow = "#ea9d34"

[colors.cursor]
cursor = "#cecacd"
text = "#575279"

[colors.hints.end]
background = "#fffaf3"
foreground = "#9893a5"

[colors.hints.start]
background = "#fffaf3"
foreground = "#797593"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#f2e9e1"
blue = "#56949f"
cyan = "#d7827e"
green = "#286983"
magenta = "#907aa9"
red = "#b4637a"
white = "#575279"
yellow = "#ea9d34"

[colors.primary]
background = "#faf4ed"
foreground = "#575279"

[colors.selection]
background = "#dfdad9"
text = "#575279"

[colors.vi_mode_cursor]
cursor = "#cecacd"
text = "#575279"
