[icons]
icons = "awesome"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = "root: $available.eng(2)"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_total_used_percents.eng(2)"
format_swap = "$swap_used_percents.eng(2)"

[[block]]
block = "sound"
driver = "pulseaudio"
headphones_indicator = true

[[block]]
block = "battery"
format = "$percentage|N/A"
hide_missing = true

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"
[block.icons_overrides]
time = ""
